#!/bin/bash
set -e
# aggressively deletes the whole cache

LOG="/var/log/loris2/cache_clean.log"

# rsync... http://www.slashroot.in/which-is-the-fastest-method-to-delete-files-in-linux
BLANK_DIR="{{ pillar.iiif.loris.storage}}/blank"
IMG_CACHE_ROOT_DIR="{{ pillar.iiif.loris.storage }}/cache-resolver"
IMG_CACHE_DP_DIR="{{ pillar.iiif.loris.storage }}/cache-general"

log_message () {
    echo -ne "$(date +[%c]) [loris-cache-clean-hard] " >> "$LOG"
    echo "$1" >> "$LOG"
}

log_message "Started loris-cache-clean-hard"

log_message "Creating blank folder to rsync"
mkdir -p $BLANK_DIR
log_message "Removing $IMG_CACHE_ROOT_DIR contents"
rsync -a --delete $BLANK_DIR/ $IMG_CACHE_ROOT_DIR/
log_message "Removing $IMG_CACHE_DP_DIR contents"
rsync -a --delete $BLANK_DIR/ $IMG_CACHE_DP_DIR/

log_message "Cache completely purged!" 
